SKILLS_LIST = [
    "Python", "Java", "JavaScript", "React", "Angular", "Vue.js", "Node.js", "Express.js",
    "Django", "Flask", "Spring Boot", "Ruby on Rails", "PHP", "Laravel", "SQL", "NoSQL",
    "PostgreSQL", "MySQL", "MongoDB", "Redis", "AWS", "Azure", "Google Cloud Platform",
    "Docker", "Kubernetes", "Git", "GitHub", "GitLab", "Bitbucket", "Jenkins", "Travis CI",
    "CircleCI", "Jira", "Confluence", "Agile", "Scrum", "Kanban", "REST API", "GraphQL",
    "Microservices", "OAuth", "JWT", "Data Structures", "Algorithms", "Machine Learning",
    "Deep Learning", "Natural Language Processing", "Computer Vision", "TensorFlow", "PyTorch",
    "Keras", "Pandas", "NumPy", "SciPy", "Scikit-learn", "Matplotlib", "Seaborn", "Tableau",
    "Power BI", "Excel", "Data Analysis", "Data Visualization", "Big Data", "Spark", "Hadoop",
    "Kafka", "ETL", "Data Warehousing", "Cloud Computing", "Cybersecurity", "Network Security",
    " penetration testing", "DevOps", "CI/CD", "Automation", "Bash", "Shell Scripting",
    "Linux", "Unix", "Windows Server", "Virtualization", "VMware", "Hyper-V", "HTML", "CSS",
    "Sass", "Less", "Bootstrap", "Tailwind CSS", "Material-UI", "UI/UX Design", "Figma",
    "Sketch", "Adobe XD", "Responsive Design", "Frontend Development", "Backend Development",
    "Full Stack Development", "Mobile Development", "iOS Development", "Android Development",
    "Swift", "Objective-C", "Kotlin", "Dart", "Flutter", "React Native", "XCode", "Android Studio",
    "Quality Assurance", "Manual Testing", "Automated Testing", "Selenium", "Cypress", "Playwright",
    "JMeter", "Load Testing", "Performance Testing", "Unit Testing", "Integration Testing",
    "End-to-End Testing", "Test Automation", "Technical Writing", "Project Management",
    "Team Leadership", "Communication", "Problem Solving", "Critical Thinking", "Adaptability",
    "Time Management", "Collaboration", "Creativity", "Attention to Detail", "Research",
    "API Development", "Database Design", "System Design", "Cloud Architecture", "Security Best Practices",
    "Code Review", "Debugging", "Performance Optimization", "WebSockets", "Real-time Applications",
    "Blockchain", "Smart Contracts", "Solidity", "EVM", "Decentralized Applications", "Data Science",
    "Business Intelligence", "Statistical Analysis", "A/B Testing", "Experiment Design",
    "Customer Service", "Sales", "Marketing", "Content Creation", "SEO", "SEM", "Social Media Marketing",
    "Email Marketing", "CRM", "ERP", "SAP", "Salesforce", "Oracle", "Microsoft Office", "G Suite"
]
